version: '3.7'

volumes:
  grafana:

services:
  grafana:
    build: .
    # image: grafana/grafana:7.3.4
    container_name: grafana
    ports:
      - 3000:3000
    restart: always
    environment:
      # GF_PLUGINS_ALLOW_LOADING_UNSIGNED_PLUGINS: "hadesarchitect-cassandra-datasource scylladb-scylla-datasource"
      GF_PLUGINS_ALLOW_LOADING_UNSIGNED_PLUGINS: "scylladb-scylla-datasource"
      GF_LOG_LEVEL: debug
    volumes:
      - grafana:/var/lib/grafana

  scylla:
    image: scylladb/scylla
    container_name: scylla
    ports:
      - 9042:9042
    restart: always
